"""Database init

Revision ID: 8338ed8cd405
Revises: 684ef753ecf0
Create Date: 2023-09-12 09:55:47.828561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8338ed8cd405'
down_revision: Union[str, None] = '684ef753ecf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('learning_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_collections_id'), 'learning_collections', ['id'], unique=False)
    op.create_index(op.f('ix_learning_collections_name'), 'learning_collections', ['name'], unique=False)
    op.create_index(op.f('ix_learning_collections_owner_id'), 'learning_collections', ['owner_id'], unique=False)
    op.create_table('learning_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('learning_collection_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['learning_collection_id'], ['learning_collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_cards_id'), 'learning_cards', ['id'], unique=False)
    op.create_table('learning_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('learning_collection_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['learning_collection_id'], ['learning_collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_sessions_id'), 'learning_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_learning_sessions_user_id'), 'learning_sessions', ['user_id'], unique=True)
    op.create_table('user_learning_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('learning_collection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['learning_collection_id'], ['learning_collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_learning_collections_id'), 'user_learning_collections', ['id'], unique=False)
    op.create_table('learning_session_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('learning_session_id', sa.Integer(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('is_passed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['learning_cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['learning_session_id'], ['learning_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_session_cards_id'), 'learning_session_cards', ['id'], unique=False)
    op.create_index(op.f('ix_learning_session_cards_learning_session_id'), 'learning_session_cards', ['learning_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_session_cards_learning_session_id'), table_name='learning_session_cards')
    op.drop_index(op.f('ix_learning_session_cards_id'), table_name='learning_session_cards')
    op.drop_table('learning_session_cards')
    op.drop_index(op.f('ix_user_learning_collections_id'), table_name='user_learning_collections')
    op.drop_table('user_learning_collections')
    op.drop_index(op.f('ix_learning_sessions_user_id'), table_name='learning_sessions')
    op.drop_index(op.f('ix_learning_sessions_id'), table_name='learning_sessions')
    op.drop_table('learning_sessions')
    op.drop_index(op.f('ix_learning_cards_id'), table_name='learning_cards')
    op.drop_table('learning_cards')
    op.drop_index(op.f('ix_learning_collections_owner_id'), table_name='learning_collections')
    op.drop_index(op.f('ix_learning_collections_name'), table_name='learning_collections')
    op.drop_index(op.f('ix_learning_collections_id'), table_name='learning_collections')
    op.drop_table('learning_collections')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
