"""Adding column

Revision ID: d0b33d325844
Revises: 8338ed8cd405
Create Date: 2023-09-12 10:25:55.073938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0b33d325844'
down_revision: Union[str, None] = '8338ed8cd405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_sessions', sa.Column('started_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learning_sessions', 'started_at')
    # ### end Alembic commands ###
