from telegram_bot.client_commands.start import register_start_command
from telegram_bot.client_commands.add_learning_collection import register_add_learning_collection_command
from telegram_bot.client_commands.run_learning_session import register_run_learning_session_command